# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='john',
            field=models.BooleanField(default=True),
        ),
    ]
