# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_john'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='john',
        ),
    ]
