# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_john'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='logo',
        ),
    ]
