# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='logo',
            field=models.FileField(default='html.jpg', upload_to=b''),
            preserve_default=False,
        ),
    ]
